interface Item {
  title: string
  description?: string
  href: string
  image?: string
}

const navbar: Record<string, Item[]> = {
  'Find student': [
    {
      title: 'Find jobs by skill',
      href: '/'
    },
    {
      title: 'Browse jobs',
      href: '/'
    },
    {
      title: 'Success stories',
      href: '/'
    },
    {
      title: 'Policies',
      href: '/'
    }
  ],
  Subjects: [
    {
      title: 'Languages',
      href: '/',
      description: 'Learn a new language or improve your language skills.',
      image: 'https://source.unsplash.com/nGrfKmtwv24'
    },
    {
      title: 'Science',
      href: '/',
      description: 'Maths, Biology, Chemistry, Physics and other scientific topics.',
      image: 'https://source.unsplash.com/gYrYa37fAKI'
    },
    {
      title: 'Programming',
      href: '/',
      description: 'Learn programming languages and computer science.',
      image: 'https://source.unsplash.com/oYKVcuxlV10'
    },
    {
      title: 'Music',
      href: '/',
      description: 'Learn to play an instrument or improve your music theory skills.',
      image: 'https://source.unsplash.com/V7z8MGbfF5Q'
    },
    {
      title: 'Art',
      href: '/',
      description: 'Drawing, painting, sculpture, photography and other art topics.',
      image: 'https://source.unsplash.com/SIoJI8hUFps'
    },
    {
      title: 'Business',
      href: '/',
      description: 'Economics, accounting, finance, marketing and other business topics.',
      image: 'https://source.unsplash.com/O2o1hzDA7iE'
    },
    {
      title: 'Humanities',
      href: '/',
      description: 'History, philosophy, literature, religion and other humanities topics.',
      image: 'https://source.unsplash.com/3ULMRQZ5APA'
    },
    {
      title: 'Test prep',
      href: '/',
      description: 'Prepare for exams like the SAT, GMAT, IELTS ...',
      image: 'https://source.unsplash.com/cbEvoHbJnIE'
    }
  ],
  'Find tutor': [
    {
      title: 'Post a job',
      href: '/'
    },
    {
      title: 'Browse tutors',
      href: '/'
    },
    {
      title: 'Student reviews',
      href: '/'
    },
    {
      title: 'How to hire',
      href: '/'
    }
  ]
}
const topics: string[] = [
  '.NET',
  '360-degree video',
  '3D Animation',
  '3D Design',
  '3D Model Maker',
  '3D Modelling',
  '3D Printing',
  '3D Rendering',
  '3ds Max',
  '4D',
  'AJAX',
  'AMQP',
  'AS400 / iSeries',
  'ASP',
  'ASP.NET',
  'Academic Cultural Capital',
  'Academic Writing Skills',
  'Academic Writing Style',
  'Academic Writing',
  'Accordion',
  'Accounting',
  'ActionScript',
  'Active Directory',
  'Active Listening',
  'Ad Planning / Buying',
  'Adaptability',
  'Adobe Air',
  'Adobe Captivate',
  'Adobe Dreamweaver',
  'Adobe Fireworks',
  'Adobe Flash',
  'Adobe InDesign',
  'Adobe Lightroom',
  'Adobe LiveCycle Designer',
  'Adobe Premiere Pro',
  'Advertisement Design',
  'Advertising',
  'Aeronautical Engineering',
  'Aerospace Engineering',
  'Affiliate Marketing',
  'Afrikaans',
  'After Effects',
  'Agile Development',
  'Agronomy',
  'Air Conditioning',
  'Albanian',
  'Algorithm',
  'Amazon Web Services',
  'Ambition',
  'Analytical Thinking',
  'Analytics',
  'Android Honeycomb',
  'Android Wear SDK',
  'Android',
  'Angular.js',
  'Animation',
  'Antenna Services',
  'Anything Goes',
  'Apache Ant',
  'Apache Solr',
  'Apache',
  'App Designer',
  'App Developer',
  'Appcelerator Titanium',
  'Apple Compressor',
  'Apple Logic Pro',
  'Apple Motion',
  'Apple iBooks Author',
  'Applescript',
  'Appliance Installation',
  'Appliance Repair',
  'Arabic',
  'Arduino',
  'Argus Monitoring Software',
  'Article Rewriting',
  'Article Submission',
  'Articles',
  'Artificial Intelligence',
  'Arts / Crafts',
  'Asbestos Removal',
  'Asphalt',
  'Assembly',
  'Asterisk PBX',
  'Astrophysics',
  'Attention to Detail',
  'Attic Access Ladders',
  'Attorney',
  'Audio Production',
  'Audio Services',
  'Audit',
  'Augmented Reality',
  'AutoCAD',
  'AutoHotkey',
  'Autodesk Inventor',
  'Autodesk Revit',
  'Automotive',
  'Autotask',
  'Awnings',
  'Axure',
  'Azure',
  'BMC Remedy',
  'BPO',
  'BSD',
  'Balsamiq',
  'Balustrading',
  'Bamboo Flooring',
  'Banjo',
  'Banner Design',
  'Basic Writing Skills',
  'Basque',
  'Bass',
  'Bengali',
  'Big Data',
  'BigCommerce',
  'Binary Analysis',
  'Biology',
  'Biotechnology',
  'Bitcoin',
  'Biztalk',
  'Blog Design',
  'Blog Install',
  'Blog',
  'Bluetooth Low Energy (BLE)',
  'Bongos',
  'Book Artist',
  'Book Writing',
  'Bookkeeping',
  'Boonex Dolphin',
  'Bosnian',
  'Bower',
  'Brackets',
  'Brain Storming',
  'Branding',
  'Brass instrument',
  'Bricklaying',
  'Broadcast Engineering',
  'Brochure Design',
  'Building Architecture',
  'Building Certifiers',
  'Building Consultants',
  'Building Designer',
  'Building Surveyors',
  'Building',
  'Bulgarian',
  'Bulk Marketing',
  'Business Analysis',
  'Business Cards',
  'Business Catalyst',
  'Business Coaching',
  'Business Intelligence',
  'Business Plans',
  'Business Writing',
  'Buyer Sourcing',
  'C Programming',
  'C# Programming',
  'C++ Programming',
  'CAD/CAM',
  'CATIA',
  'CGI',
  'CLIPS',
  'CMS',
  'COBOL',
  'CRE Loaded',
  'CRM',
  'CS-Cart',
  'CSS',
  'CUDA',
  'CakePHP',
  'Call Center',
  'Call Control XML',
  'Capture NX2',
  'Caricature / Cartoons',
  'Carpentry',
  'Carpet Repair / Laying',
  'Carports',
  'Cartography / Maps',
  'Carwashing',
  'CasperJS',
  'Cassandra',
  'Catalan',
  'Catch Phrases',
  'Ceilings',
  'Cello',
  'Cement Bonding Agents',
  'Chef Configuration Management',
  'Chemical Engineering',
  'Chordiant',
  'Christmas',
  'Chrome OS',
  'Cinema 4D',
  'Circuit Design',
  'Cisco',
  'Civil Engineering',
  'Clarinet',
  'Classifieds Posting',
  'Clean Technology',
  'Cleaning Carpet',
  'Cleaning Domestic',
  'Cleaning Upholstery',
  'Climate Sciences',
  'Clothesline',
  'Cloud Computing',
  'Coating Materials',
  'Cocoa',
  'Codeigniter',
  'Coding',
  'Cold Fusion',
  'Collaboration',
  'Columns',
  'Commercial Cleaning',
  'Commercials',
  'Commitment',
  'Communication Skills',
  'Communications',
  'Compare and Contrast',
  'Compliance',
  'Computer Graphics',
  'Computer Help',
  'Computer Security',
  'Concept Art',
  'Concept Design',
  'Concreting',
  'Conflict Resolution',
  'Conscientiousness',
  'Construction Monitoring',
  'Content Writing',
  'Contracts',
  'Convergent Thinking',
  'Conversion Rate Optimization',
  'Cooking / Recipes',
  'Cooperation',
  'Copy Typing',
  'Copywriting',
  'Corporate Identity',
  'Courses',
  'Covers / Packaging',
  'Creative Design',
  'Creative Writing',
  'Creativity',
  'Critical Reading',
  'Critical Thinking Skills',
  'Croatian',
  'Cryptography',
  'Crystal Reports',
  'CubeCart',
  'Cultural Competence',
  'Customer Service',
  'Customer Support',
  'Czech',
  'DDS',
  'DNS',
  'DOS',
  'Damp Proofing',
  'Danish',
  'Dari',
  'Dart',
  'Data Analysis',
  'Data Entry',
  'Data Mining',
  'Data Processing',
  'Data Science',
  'Data Warehousing',
  'DataLife Engine',
  'Database Administration',
  'Database Development',
  'Database Programming',
  'Dating',
  'Debate Skills',
  'Debian',
  'Debugging',
  'Decking',
  'Deconstructing Texts',
  'Decoration',
  'Dedication',
  'Deductive Thinking',
  'Delivery',
  'Delphi',
  'Demolition',
  'Dependability',
  'Design',
  'Desktop Support',
  'Determination',
  'Differentiation',
  'Digital Design',
  'Digital Literacy',
  'Diligence',
  'Discourse Analysis',
  'Disposals',
  'Divergent Thinking',
  'Django',
  'DotNetNuke',
  'Drafting',
  'Drains',
  'Drones',
  'Drums',
  'Drupal',
  'Dthreejs',
  'Dutch',
  'Dynamics',
  'ERP',
  'Editing',
  'Education / Tutoring',
  'Efficiency',
  'Elasticsearch',
  'Electrical Engineering',
  'Electricians',
  'Electronic Forms',
  'Electronics',
  'Email Developer',
  'Email Handling',
  'Email Marketing',
  'Embedded Software',
  'Ember.js',
  'Empirical Thinking',
  'Employment Law',
  'Energy',
  'Engineering Drawing',
  'Engineering',
  'English (UK)',
  'English (US)',
  'English Grammar',
  'English Spelling',
  'Entrepreneurship',
  'Equipment Hire',
  'Erlang',
  'Estonian',
  'Ethical Thinking',
  'Etsy',
  'Event Planning',
  'Event Staffing',
  'Excavation',
  'Excel',
  'Experimental Design',
  'Express JS',
  'Expression Engine',
  'Extensions / Additions',
  'FPGA',
  'Face Recognition',
  'Facebook Marketing',
  'Fashion Design',
  'Fashion Modeling',
  'Fencing',
  'Feng Shui',
  'Fiction',
  'FileMaker',
  'Filipino',
  'Filmmaking',
  'Final Cut Pro',
  'Finale / Sibelius',
  'Finance',
  'Financial Analysis',
  'Financial Markets',
  'Financial Planning',
  'Financial Research',
  'Finite Element Analysis',
  'Finnish',
  'Firefox',
  'Flash 3D',
  'Flashmob',
  'Flex',
  'Flexible Thinking Skills',
  'Floor Coatings',
  'Flooring',
  'Flow Charts',
  'Flute',
  'Flyer Design',
  'Flyscreens',
  'Focus',
  'Food Takeaway',
  'Format / Layout',
  'Fortran',
  'Forum Posting',
  'Forum Software',
  'Frames / Trusses',
  'FreeSwitch',
  'Freelance',
  'FreelancerAPI',
  'French',
  'Fundraising',
  'Furniture Assembly',
  'Furniture Design',
  'GIMP',
  'GPGPU',
  'GPS',
  'Game Consoles',
  'Game Design',
  'Game Development',
  'GameSalad',
  'Gamification',
  'GarageBand',
  'Gardening',
  'Gas Fitting',
  'Genealogy',
  'General Labor',
  'General Office',
  'Genetic Engineering',
  'Geolocation',
  'Geology',
  'Geospatial',
  'Geotechnical Engineering',
  'German',
  'Ghostwriting',
  'Git',
  'Glass / Mirror / Glazing',
  'Global Citizenship',
  'GoPro',
  'Goal Setting',
  'Golang',
  'Google Adsense',
  'Google Adwords',
  'Google Analytics',
  'Google App Engine',
  'Google Cardboard',
  'Google Cloud Storage',
  'Google Earth',
  'Google Maps API',
  'Google Plus',
  'Google SketchUp',
  'Google Web Toolkit',
  'Google Webmaster Tools',
  'Google Website Optimizer',
  'Grails',
  'Grant Writing',
  'Graphic Design',
  'Grease Monkey',
  'Greek',
  'Growth Hacking',
  'Growth Mindset',
  'Grunt',
  'Guitar',
  'Guttering',
  'HBase',
  'HP Openview',
  'HTML',
  'Hadoop',
  'Hair Styles',
  'Handyman',
  'Harp',
  'Haskell',
  'Health',
  'Heating Systems',
  'Hebrew',
  'Helpdesk',
  'Heroku',
  'Hindi',
  'History',
  'Hive',
  'Home Automation',
  'Home Design',
  'Home Organization',
  'HomeKit',
  'Hot Water',
  'House Cleaning',
  'Housework',
  'Human Resources',
  'Human Sciences',
  'Humility',
  'Hungarian',
  'Hypothesizing',
  'IBM BPM',
  'IBM Tivoli',
  'IBM Websphere Transformation Tool',
  'IIS',
  'IKEA Installation',
  'ISO9001',
  'ITIL',
  'Icon Design',
  'Identifying Fallacies',
  'Illustration',
  'Illustrator',
  'Imaging',
  'Independent Thought',
  'Indonesian',
  'Inductive Thinking',
  'Industrial Design',
  'Industrial Engineering',
  'Infographics',
  'Information Literacy',
  'Initiative',
  'Insightfulness',
  'Inspections',
  'Installation',
  'Instrument',
  'Instrumentation',
  'Insurance',
  'Integrity',
  'Intellectual Curiosity',
  'Intellectual Curiosity',
  'Interior Design',
  'Interiors',
  'Internet Marketing',
  'Internet Research',
  'Internet Security',
  'Interpersonal Skills',
  'Interpreter',
  'Interspire',
  'Intuit QuickBooks',
  'Inventory Management',
  'Investment Research',
  'Invitation Design',
  'Ionic Framework',
  'Italian',
  'J2EE',
  'J2ME',
  'JD Edwards CNC',
  'JDF',
  'JSON',
  'JSP',
  'Jabber',
  'Japanese',
  'Java',
  'JavaFX',
  'Javascript',
  'Jewellery',
  'Joomla',
  'Journalist',
  'Kannada',
  'Kinect',
  'Kitchen',
  'Knockout.js',
  'Korean',
  'LESS/Sass/SCSS',
  'LINQ',
  'LaTeX',
  'LabVIEW',
  'Label Design',
  'Landing Pages',
  'Landscape Design',
  'Landscaping / Gardening',
  'Landscaping',
  'Laravel',
  'Latvian',
  'Laundry and Ironing',
  'Lawn Mowing',
  'Leadership',
  'Leads',
  'Leap Motion SDK',
  'Legal Research',
  'Legal Writing',
  'Legal',
  'Library Skills',
  'Life Coaching',
  'Lighting',
  'Linear Programming',
  'Link Building',
  'Linnworks Order Management',
  'Linux',
  'Lisp',
  'Lithuanian',
  'LiveCode',
  'Locksmith',
  'Logic',
  'Logistics / Shipping',
  'Logo Design',
  'Lotus Notes',
  'Lua',
  'Lute',
  'MLM',
  'MMORPG',
  'MODx',
  'MQTT',
  'MVC',
  'MYOB',
  'Mac OS',
  'Macedonian',
  'Machine Learning',
  'Magento',
  'Magic Leap',
  'Mailchimp',
  'Mailwizz',
  'Make Up',
  'Makerbot',
  'Malay',
  'Malayalam',
  'Maltese',
  'Management',
  'Mandolin',
  'Manufacturing Design',
  'Manufacturing',
  'Map Reduce',
  'MariaDB',
  'Market Research',
  'Marketing',
  'Marketplace Service',
  'Materials Engineering',
  'Mathematical Thinking',
  'Mathematics',
  'Matlab and Mathematica',
  'Maya',
  'Mechanical Engineering',
  'Mechatronics',
  'Media Literacy',
  'Medical Writing',
  'Medical',
  'Metatrader',
  'MeteorJS',
  'Metro',
  'Microbiology',
  'Microcontroller',
  'Microsoft Access',
  'Microsoft Exchange',
  'Microsoft Expression',
  'Microsoft Hololens',
  'Microsoft Office',
  'Microsoft Outlook',
  'Microsoft SQL Server',
  'Microsoft Visio',
  'Microstation',
  'Millwork',
  'Mining Engineering',
  'Minitlab',
  'Mobile App Testing',
  'Mobile Phone',
  'MonetDB',
  'Moodle',
  'Mortgage Brokering',
  'Motion Graphics',
  'Moving',
  'Multi-Tasking',
  'Mural Painting',
  'Music',
  'MySQL',
  'MySpace',
  'Nanotechnology',
  'Natural Language Processing',
  'Natural Language',
  'Network Administration',
  'Newsletters',
  'NextJS',
  'Nginx',
  'Ning',
  'Nintex Forms',
  'Nintex Workflow',
  'NoSQL Couch / Mongo',
  'Norwegian',
  'Note Taking',
  'Nutrition',
  'OAuth',
  'OCR',
  'OSCommerce',
  'Objective C',
  'Objectivity (Bias Minimization)',
  'Oboe',
  'Oculus Mobile SDK',
  'Odoo',
  'Online Etiquette',
  'Online Writing',
  'Open Cart',
  'Open Journal Systems',
  'Open-Mindedness',
  'OpenBravo',
  'OpenCL',
  'OpenGL',
  'OpenSSL',
  'OpenSceneGraph',
  'OpenStack',
  'OpenVMS',
  'Oracle',
  'Order Processing',
  'Organizational Change Management',
  'Organizational Skills',
  'PCB Layout',
  'PDF',
  'PEGA PRPC',
  'PHP',
  'PICK Multivalue DB',
  'PLC / SCADA',
  'PSD to HTML',
  'PSD2CMS',
  'Package Design',
  'Packing / Shipping',
  'Painting',
  'Palm',
  'Papiamento',
  'Parallax Scrolling',
  'Parallel Processing',
  'Parallels Automation',
  'Parallels Desktop',
  'Paraphrasing',
  'Patents',
  'Patience',
  'Pattern Making',
  'Pattern Matching',
  'Pavement',
  'PayPal API',
  'Payroll',
  'Paytrace',
  'PencilBlue CMS',
  'Pentaho',
  'PeopleSoft',
  'Percussion',
  'Periscope',
  'Perl',
  'Perseverance',
  'Persistence',
  'Personal Development',
  'Personal Responsibility',
  'Persuasiveness',
  'Pest Control',
  'Pet Sitting',
  'Petroleum Engineering',
  'Phone Support',
  'PhoneGap',
  'Photo Editing',
  'Photography',
  'Photoshop Coding',
  'Photoshop',
  'Physics',
  'Piano',
  'Pickup',
  'Pinterest',
  'Piping',
  'Plesk',
  'Plugin',
  'Plumbing',
  'Poet',
  'Poetry',
  'Polish',
  'Portuguese',
  'Post-Production',
  'Poster Design',
  'PostgreSQL',
  'Powerpoint',
  'Powershell',
  'Pre-production',
  'Presentation Skills',
  'Presentations',
  'Press Releases',
  'Prestashop',
  'Prezi',
  'Print',
  'Prioritization',
  'Proactiveness',
  'Problem-Solving Skills',
  'Procurement',
  'Product Descriptions',
  'Product Design',
  'Product Management',
  'Product Sourcing',
  'Professionalism',
  'Programming',
  'Project Management',
  'Project Scheduling',
  'Prolog',
  'Proofreading',
  'Proofreading',
  'Property Development',
  'Property Law',
  'Property Management',
  'Proposal/Bid Writing',
  'Protoshare',
  'Psychology',
  'Public Relations',
  'Public Speaking Skills',
  'Publishing',
  'Punctuality',
  'Punjabi',
  'Puppet',
  'PyTorch',
  'Python',
  'QlikView',
  'Qualtrics Survey Platform',
  'Quantum',
  'QuarkXPress',
  'QuickBase',
  'R Programming Language',
  'REALbasic',
  'RESTful',
  'RTOS',
  'RWD',
  'RapidWeaver',
  'Raspberry Pi',
  'Ray-tracing',
  'React.js',
  'Reading for Meaning',
  'Real Estate',
  'Realism',
  'Recorder',
  'Recruitment',
  'Red Hat',
  'Redis',
  'Redshift',
  'Referencing',
  'Regular Expressions',
  'Reliability',
  'Remote Sensing',
  'Removalist',
  'Renewable Energy Design',
  'Report Writing',
  'Research',
  'Resourcefulness',
  'Responsiveness',
  'Resumes',
  'Reviews',
  'Risk Management',
  'Robotics',
  'Rocket Engine',
  'Romanian',
  'Roofing',
  'Ruby on Rails',
  'Ruby',
  'Russian',
  'SAP',
  'SAS',
  'SEO',
  'SPSS Statistics',
  'SQL',
  'SQLite',
  'Sales',
  'Salesforce App Development',
  'Samsung Accessory SDK',
  'Saxophone',
  'Scala',
  'Scheme',
  'Scientific Research',
  'Screenwriting',
  'Script Install',
  'Scrum Development',
  'Scrum',
  'Sculpturing',
  'Search Engine Marketing',
  'Self-Assessment',
  'Self-Belief',
  'Self-Control',
  'Self-Directed Learning',
  'Self-Discipline',
  'Self-Editing',
  'Self-Reflection',
  'Sencha / YahooUI',
  'Serbian',
  'Sewing',
  'Sharepoint',
  'Shell Script',
  'Shopify',
  'Short Stories',
  'Siebel',
  'Sign Design',
  'Silverlight',
  'Simplified Chinese (China)',
  'Slogans',
  'Slovakian',
  'Slovenian',
  'Smarty PHP',
  'Snapchat',
  'Social Engine',
  'Social Media Marketing',
  'Social Networking',
  'Social Skills',
  'Socket IO',
  'Software Architecture',
  'Software Development',
  'Software Testing',
  'Solaris',
  'Solidworks',
  'Sound Design',
  'Spanish (Spain)',
  'Spanish',
  'Spark',
  'Specialization',
  'Speech Writing',
  'Sphinx',
  'Splunk',
  'Sports',
  'Squarespace',
  'Squid Cache',
  'Startups',
  'Stationery Design',
  'Statistical Analysis',
  'Statistics',
  'Steam API',
  'Sticker Design',
  'Storage Area Networks',
  'Storyboard',
  'Strapi CMS',
  'Strategic Thinking',
  'Stress Management Skills',
  'Strings',
  'Stripe',
  'Structural Engineering',
  'Study Skills',
  'Subversion',
  'SugarCRM',
  'Summarizing',
  'Supplier Sourcing',
  'Surfboard Design',
  'Svelte',
  'Swedish',
  'Swift',
  'Symbian',
  'Symfony PHP',
  'System Admin',
  'T-Shirts',
  'TYPO3',
  'Tableau',
  'Tally Definition Language',
  'Tamil',
  'TaoBao API',
  'Tattoo Design',
  'Tax Law',
  'Tax',
  'Teamwork Skills',
  'Technical Support',
  'Technical Writing',
  'Tekla Structures',
  'Telecommunications Engineering',
  'Telemarketing',
  'Telephone Handling',
  'Telugu',
  'Templates',
  'Tenacity',
  'Test Automation',
  'TestStand',
  'Testing / QA',
  'Textile Engineering',
  'Thai',
  'Tibco Spotfire',
  'Tiling',
  'Time Management',
  'Titanium',
  'Tizen SDK for Wearables',
  'Traditional Chinese (Hong Kong)',
  'Traditional Chinese (Taiwan)',
  'Training',
  'Transcription',
  'Translation',
  'Travel Writing',
  'Triangulation',
  'Troubleshooting',
  'Trumpet',
  'Tumblr',
  'Turkish',
  'Twitter',
  'Typescript',
  'Typography',
  'UML Design',
  'UNIX',
  'Ukrainian',
  'Ukulele',
  'Umbraco',
  'Unit4 Business World',
  'Unity 3D',
  'Urdu',
  'Usability Testing',
  'User Experience Design',
  'User Interface / IA',
  'User Interface Design',
  'VB.NET',
  'VHDL',
  'VMware',
  'VPS',
  'Valuation / Appraisal',
  'Varnish Cache',
  'Vectorization',
  'Veeam',
  'Vehicle Signage',
  'Verilog',
  'VertexFX',
  'Video Broadcasting',
  'Video Editing',
  'Video Production',
  'Video Services',
  'Video Upload',
  'Videography',
  'Vietnamese',
  'Viola',
  'Violin',
  'Viral Marketing',
  'Virtual Assistant',
  'Virtual Worlds',
  'Virtuemart',
  'Virtuozzo',
  'Visa / Immigration',
  'Visual Arts',
  'Visual Basic for Apps',
  'Visual Basic',
  'Visual Foxpro',
  'Visual Merchandising',
  'Visualization',
  'VoIP',
  'Voice Artist',
  'Voice Talent',
  'VoiceXML',
  'Volusion',
  'Vuforia',
  'WHMCS',
  'WIKI',
  'WPF',
  'WatchKit',
  'Web Hosting',
  'Web Scraping',
  'Web Search',
  'Web Security',
  'Web Services',
  'WebOS',
  'Website Design',
  'Website Management',
  'Website Testing',
  'Weebly',
  'Welsh',
  'Wikipedia',
  'Windows API',
  'Windows CE',
  'Windows Desktop',
  'Windows Server',
  'Wireframes',
  'Wireless',
  'Wix',
  'Wolfram',
  'WooCommerce',
  'Word Processing',
  'Word',
  'WordPress',
  'Work Ethic',
  'Workshops',
  'Wufoo',
  'XML',
  'XMPP',
  'XPages',
  'XQuery',
  'XSLT',
  'Xamarin',
  'Xero',
  'Xojo',
  'Xoops',
  'Yard Work / Removal',
  'Yarn',
  'Yiddish',
  'Yii',
  'Zbrush',
  'Zen Cart',
  'Zend',
  'Zendesk',
  'Zesty CMS',
  'Zoho',
  'backbone.js',
  'eBooks',
  'eCommerce',
  'eLearning Designer',
  'eLearning',
  'ePub',
  'edX',
  'iBeacon',
  'iMovie',
  'jQuery / Prototype',
  'node.js',
  'vBulletin',
  'vTiger',
  'webMethods',
  'x86/x64 Assembler'
]

export { topics, navbar }
